version: '3.8'

services:
  db:
    image: mongo:6-jammy
    container_name: goalbum_mongo
    ports:
      - '27017:27017'
    volumes:
      - goalbum_mongo_data:/data/db
    restart: always

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goalbum_api
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://db:27017/goalbum
    depends_on:
      - db
    restart: always

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
        - VITE_APP_OWNER=${VITE_APP_OWNER:-camilonavarro14}
        - VITE_APP_NAME=${VITE_APP_NAME:-Goalbum}
        - VITE_TERMS_URL=${VITE_TERMS_URL:-}
        - VITE_APP_ENV=${VITE_APP_ENV:-}
    container_name: goalbum_web
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - VITE_APP_OWNER=${VITE_APP_OWNER:-camilonavarro14}
      - VITE_APP_NAME=${VITE_APP_NAME:-Goalbum}
      - VITE_TERMS_URL=${VITE_TERMS_URL:-}
      - VITE_APP_ENV=${VITE_APP_ENV:-}
    depends_on:
      - api
    restart: always

volumes:
  goalbum_mongo_data:
